### ISSUE TITLE
Flickr 1 million image links update

### ISSUE THREAD

**Issue by mialondon** [bl-rses/top-ship#6]
An issue for the BL Labs tech lead, when they start:

John Gostick has written up a description of two fixes that need to be done for the Flickr million images. One is due to changes in internal systems and the other would apparently always have been an issue. As you're recruiting for the RSE I thought it might be a useful real world task to test people on, as well as a useful early task for them when they start?

A number of the images in the British Library collection on Flickr (e.g. https://www.flickr.com/photos/britishlibrary/11111708484/ ) contain a link in their description to view the original item in ‘the British Library's itemViewer’, and at least some of those underlying URLs also link to http://itemviewer.bl.uk, which was an internal only DNS name for itemVIEWER that was never accessible internally, so these are (and have always been) dead links externally.

itemVIEWER itself is no longer used and is being decommissioned, as all digitised content is now displayed in Universal Viewer instead via the URL http://access.bl.uk/item/viewer.

Therefore can somebody please update the image descriptions in Flickr as follows:

1.	Change any references to itemVIEWER to Universal Viewer (or a more generic name like ‘digitised item viewer’?)
2.	Change the underlying URLs so that:
a.	access.bl.uk/item/viewer is used instead of itemviewer.bl.uk
b.	The ‘L-ARK’ persistent identifier for each item is used in the URL instead of the old UID identifier, e.g. lsidyv3cafc556. A list of L-ARKs that replace each UID can be provided if required.

There's a third potential change that's still to be confirmed. MS Books and Playbills items link to a PDF access service that's likely to be retired soon, which would mean replacing the 'Download the PDF for this book' with text saying it can be downloaded from the BL viewer.

**Comment by mialondon** [comment]
@harryjmoss this is the issue I emailed about during the week

**Comment by harryjmoss** [comment]
Thanks @mialondon! I'll set up a meeting with Mahendra to go through the previous procedure for this.

**Comment by mialondon** [comment]
Given the existence of https://docs.google.com/document/d/1cZmV3GjZje9In4YmhhnQshSbT1D215dVc6U-iyFueYY/edit I'm going to close this as a duplicate.
